import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { createRequire } from 'node:module';
import { chromium } from 'playwright';
const require = createRequire(import.meta.url);
const output = path.resolve('../../artifacts/article-timeline');
await fs.mkdir(output, {recursive:true});
const browser = await chromium.launch({channel:'chrome',headless:true});
const context = await browser.newContext({viewport:{width:390,height:844},hasTouch:true});
await context.route('https://example.org/timeline-river.png', route => route.fulfill({path:path.resolve('fixtures/timeline-river.png'),contentType:'image/png'}));
await context.route('https://example.org/missing-image.png', route => route.fulfill({status:404,body:''}));
const page = await context.newPage();
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
try {
const url=process.env.RILL_BROWSER_URL || 'http://127.0.0.1:3890';
assert.ok(['127.0.0.1','localhost'].includes(new URL(url).hostname));
await page.goto(`${url}/?timeline=fixture`);
await page.waitForFunction(()=>window.rillUiAudit?.().appBusy==='false');
await page.evaluate(()=>window.rillOpenQueue());
await page.locator('.story-card').first().waitFor();
await page.waitForTimeout(500);
await page.locator('.story-card').first().evaluate(e=>e.blur());
const results=[];
for (const width of [320,390,430,768,1440]) {
 await page.setViewportSize({width,height:900});
 await page.waitForTimeout(200);
 await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});
 const result=await page.evaluate(async()=>({ui:window.rillUiAudit(),violations:(await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations}));
 results.push({width,...result});
 await page.screenshot({path:path.join(output,`${width}-timeline.png`)});
 assert.equal(result.ui.horizontalOverflow,false);
}
await page.setViewportSize({width:390,height:844});
const broken=page.locator('img[src="https://example.org/missing-image.png"]');
await broken.evaluate(e=>e.loading='eager');
await page.waitForFunction(()=>document.querySelector('img[src="https://example.org/missing-image.png"]').hidden);
await page.evaluate(()=>document.getElementById('story_list').scrollTop=0);
await page.locator('.story-save').first().focus();
await page.keyboard.press('Enter');
await page.locator('.story-save[aria-pressed="true"]').first().waitFor();
await page.waitForTimeout(500);
assert.equal(await page.evaluate(()=>document.activeElement.textContent.trim()),'Saved');
await page.locator('#queue-notice-dismiss').click();
await page.locator('.story-read').first().click();
await page.getByText('Marked read',{exact:true}).waitFor();
assert.equal(await page.locator('#reader-document').count(),0);
await page.locator('#queue-undo').click();
await page.getByText('Marked unread',{exact:true}).waitFor();
await page.locator('#queue-notice-dismiss').click();
await page.locator('.story-card').first().evaluate(e=>e.blur());
await page.evaluate(()=>document.getElementById('story_list').scrollTop=0);
await page.screenshot({path:path.join(output,'390-final.png')});
const touch = await context.newCDPSession(page);
const swipe = async (dx,dy=0) => {
 const bounds=await page.locator('.story-card').first().boundingBox();
 const x=Math.min(300,bounds.x+bounds.width-30), y=bounds.y+35;
 await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});
 await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx/2,y:y+dy/2}]});
 await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx,y:y+dy}]});
 await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
};
const firstId=await page.locator('.story-row').first().getAttribute('data-entry-id');
await swipe(-80);
await page.waitForFunction(()=>document.querySelector('.story-swipe-tray').getAttribute('aria-hidden')==='false');
await page.screenshot({path:path.join(output,'390-swipe.png')});
await page.locator('.story-swipe-button').first().focus();
await page.keyboard.press('Escape');
await swipe(-220);
await page.getByText('Marked read',{exact:true}).waitFor();
assert.equal(await page.locator('#reader-document').count(),0);
assert.notEqual(await page.locator('.story-row').first().getAttribute('data-entry-id'),firstId);
await page.screenshot({path:path.join(output,'390-undo.png')});
await page.locator('#queue-undo').click();
await page.getByText('Marked unread',{exact:true}).waitFor();
assert.equal(await page.locator(`[data-entry-id="${firstId}"].story-row`).count(),1);
await page.locator('#queue-notice-dismiss').click();
await page.evaluate(()=>document.getElementById('story_list').scrollTop=0);
await swipe(-5,-80);
assert.equal(await page.locator(`[data-entry-id="${firstId}"].story-row`).count(),1);
assert.equal(await page.locator('.story-swipe-tray').first().getAttribute('aria-hidden'),'true');
await page.evaluate(()=>document.getElementById('story_list').scrollTop=0);
await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});
await page.screenshot({path:path.join(output,'390-dark.png')});
await page.evaluate(()=>document.documentElement.style.setProperty('font-size','200%','important'));
await page.waitForTimeout(200);
assert.ok(await page.evaluate(()=>parseFloat(getComputedStyle(document.documentElement).fontSize))>=28);
await page.screenshot({path:path.join(output,'390-large-text.png')});
const darkViolations=await page.evaluate(async()=>(await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations);
results.push({state:'dark-large-text',violations:darkViolations});
assert.equal(await page.evaluate(()=>window.rillUiAudit().horizontalOverflow),false);
assert.equal(results.flatMap(r=>r.violations).length,0);
await fs.writeFile(path.join(output,'results.json'),JSON.stringify({results,errors},null,2));
assert.equal(errors.length,0);
} finally {await browser.close();}
